spring.application.name=LearnWave
server.port=8080
spring.datasource.url=${LearnWave.mssql.somee.com}
spring.datasource.username=${IsabellyP}
spring.datasource.password=${Isa425366}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
